# Generated by Django 3.2.9 on 2022-02-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20220216_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
