# Generated by Django 3.2.9 on 2022-02-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_auto_20220218_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='budget',
        ),
    ]
